plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
	id 'com.github.johnrengelman.shadow' version '8.1.1' // se for usar shadowJar
}

group = 'com.construcaosoftware'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'


repositories {
	mavenCentral()
}

//java {
//	toolchain {
//		languageVersion = JavaLanguageVersion.of(17)
//	}
//}

jacoco {
	toolVersion = "0.8.10"
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required.set(true)
		html.required.set(true)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}


dependencies {
	// Dependências Spring
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-data-rest'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	runtimeOnly 'org.postgresql:postgresql'

	// Lombok e MapStruct
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	// AWS Serverless Java Container
	implementation 'com.amazonaws.serverless:aws-serverless-java-container-springboot3:2.0.1'

	// Testes
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}

// Configura o JAR gerado pelo Shadow para ser usado no Lambda
tasks.named('shadowJar') {
	archiveBaseName.set('demo')
	archiveClassifier.set('all') // resultado: demo-0.0.1-SNAPSHOT-all.jar
	archiveVersion.set('0.0.1-SNAPSHOT')
}

// Se você quiser, desabilite o bootJar para não gerar o jar padrão do Spring
tasks.named('bootJar') {
	enabled = false
}